level1 = [
    {"on":False,"location":[0,0], "visible":False, "explored":False, "wall":False},
    {"on":False,"location":[1,0], "visible":False, "explored":False, "wall":False},
    {"on":False,"location":[2,0], "visible":False, "explored":False, "wall":False},
    {"on":False,"location":[3,0], "visible":False, "explored":False, "wall":True},
    {"on":False,"location":[4,0], "visible":False, "explored":False, "wall":False},
    {"on":False,"location":[5,0], "visible":False, "explored":False, "wall":False},
    {"on":False,"location":[6,0], "visible":False, "explored":False, "wall":False},
    {"on":False,"location":[7,0], "visible":False, "explored":False, "wall":False},
    {"on":False,"location":[8,0], "visible":False, "explored":False, "wall":False},
    {"on":False,"location":[9,0], "visible":False, "explored":False, "wall":False},

    {"on":False,"location":[0,1], "visible":False, "explored":False, "wall":False},
    {"on":False,"location":[1,1], "visible":False, "explored":False, "wall":False},
    {"on":False,"location":[2,1], "visible":False, "explored":False, "wall":False},
    {"on":False,"location":[3,1], "visible":False, "explored":False, "wall":True},
    {"on":False,"location":[4,1], "visible":False, "explored":False, "wall":False},
    {"on":False,"location":[5,1], "visible":False, "explored":False, "wall":True},
    {"on":False,"location":[6,1], "visible":False, "explored":False, "wall":True},
    {"on":False,"location":[7,1], "visible":False, "explored":False, "wall":True},
    {"on":False,"location":[8,1], "visible":False, "explored":False, "wall":False},
    {"on":False,"location":[9,1], "visible":False, "explored":False, "wall":False},

    {"on":False,"location":[0,2], "visible":False, "explored":False, "wall":False},
    {"on":False,"location":[1,2], "visible":False, "explored":False, "wall":False},
    {"on":False,"location":[2,2], "visible":False, "explored":False, "wall":True},
    {"on":False,"location":[3,2], "visible":False, "explored":False, "wall":True},
    {"on":False,"location":[4,2], "visible":False, "explored":False, "wall":False},
    {"on":False,"location":[5,2], "visible":False, "explored":False, "wall":False},
    {"on":False,"location":[6,2], "visible":False, "explored":False, "wall":False},
    {"on":False,"location":[7,2], "visible":False, "explored":False, "wall":True},
    {"on":False,"location":[8,2], "visible":False, "explored":False, "wall":True},
    {"on":False,"location":[9,2], "visible":False, "explored":False, "wall":False},

    {"on":False,"location":[0,3], "visible":False, "explored":False, "wall":True},
    {"on":False,"location":[1,3], "visible":False, "explored":False, "wall":False},
    {"on":False,"location":[2,3], "visible":False, "explored":False, "wall":False},
    {"on":False,"location":[3,3], "visible":False, "explored":False, "wall":False},
    {"on":False,"location":[4,3], "visible":False, "explored":False, "wall":False},
    {"on":False,"location":[5,3], "visible":False, "explored":False, "wall":False},
    {"on":False,"location":[6,3], "visible":False, "explored":False, "wall":False},
    {"on":False,"location":[7,3], "visible":False, "explored":False, "wall":True},
    {"on":False,"location":[8,3], "visible":False, "explored":False, "wall":False},
    {"on":False,"location":[9,3], "visible":False, "explored":False, "wall":False},

    {"on":False,"location":[0,4], "visible":False, "explored":False, "wall":True},
    {"on":False,"location":[1,4], "visible":False, "explored":False, "wall":True},
    {"on":False,"location":[2,4], "visible":False, "explored":False, "wall":True},
    {"on":False,"location":[3,4], "visible":False, "explored":False, "wall":False},
    {"on":False,"location":[4,4], "visible":False, "explored":False, "wall":True},
    {"on":False,"location":[5,4], "visible":False, "explored":False, "wall":False},
    {"on":False,"location":[6,4], "visible":False, "explored":False, "wall":False},
    {"on":False,"location":[7,4], "visible":False, "explored":False, "wall":True},
    {"on":False,"location":[8,4], "visible":False, "explored":False, "wall":False},
    {"on":False,"location":[9,4], "visible":False, "explored":False, "wall":False},

    {"on":False,"location":[0,5], "visible":False, "explored":False, "wall":False},
    {"on":False,"location":[1,5], "visible":False, "explored":False, "wall":False},
    {"on":False,"location":[2,5], "visible":False, "explored":False, "wall":False},
    {"on":False,"location":[3,5], "visible":False, "explored":False, "wall":False},
    {"on":False,"location":[4,5], "visible":False, "explored":False, "wall":True},
    {"on":False,"location":[5,5], "visible":False, "explored":False, "wall":False},
    {"on":False,"location":[6,5], "visible":False, "explored":False, "wall":False},
    {"on":False,"location":[7,5], "visible":False, "explored":False, "wall":False},
    {"on":False,"location":[8,5], "visible":False, "explored":False, "wall":False},
    {"on":False,"location":[9,5], "visible":False, "explored":False, "wall":False},

    {"on":False,"location":[0,6], "visible":False, "explored":False, "wall":False},
    {"on":False,"location":[1,6], "visible":False, "explored":False, "wall":False},
    {"on":False,"location":[2,6], "visible":False, "explored":False, "wall":False},
    {"on":False,"location":[3,6], "visible":False, "explored":False, "wall":False},
    {"on":False,"location":[4,6], "visible":False, "explored":False, "wall":True},
    {"on":False,"location":[5,6], "visible":False, "explored":False, "wall":False},
    {"on":False,"location":[6,6], "visible":False, "explored":False, "wall":True},
    {"on":False,"location":[7,6], "visible":False, "explored":False, "wall":True},
    {"on":False,"location":[8,6], "visible":False, "explored":False, "wall":True},
    {"on":False,"location":[9,6], "visible":False, "explored":False, "wall":False},

    {"on":False,"location":[0,7], "visible":False, "explored":False, "wall":False},
    {"on":False,"location":[1,7], "visible":False, "explored":False, "wall":False},
    {"on":False,"location":[2,7], "visible":False, "explored":False, "wall":False},
    {"on":False,"location":[3,7], "visible":False, "explored":False, "wall":False},
    {"on":False,"location":[4,7], "visible":False, "explored":False, "wall":False},
    {"on":False,"location":[5,7], "visible":False, "explored":False, "wall":False},
    {"on":False,"location":[6,7], "visible":False, "explored":False, "wall":True},
    {"on":False,"location":[7,7], "visible":False, "explored":False, "wall":False},
    {"on":False,"location":[8,7], "visible":False, "explored":False, "wall":False},
    {"on":False,"location":[9,7], "visible":False, "explored":False, "wall":False},

    {"on":False,"location":[0,8], "visible":False, "explored":False, "wall":False},
    {"on":False,"location":[1,8], "visible":False, "explored":False, "wall":True},
    {"on":False,"location":[2,8], "visible":False, "explored":False, "wall":True},
    {"on":False,"location":[3,8], "visible":False, "explored":False, "wall":False},
    {"on":False,"location":[4,8], "visible":False, "explored":False, "wall":False},
    {"on":False,"location":[5,8], "visible":False, "explored":False, "wall":False},
    {"on":False,"location":[6,8], "visible":False, "explored":False, "wall":True},
    {"on":False,"location":[7,8], "visible":False, "explored":False, "wall":False},
    {"on":False,"location":[8,8], "visible":False, "explored":False, "wall":False},
    {"on":False,"location":[9,8], "visible":False, "explored":False, "wall":False},

    {"on":False,"location":[0,9], "visible":False, "explored":False, "wall":False},
    {"on":False,"location":[1,9], "visible":False, "explored":False, "wall":False},
    {"on":False,"location":[2,9], "visible":False, "explored":False, "wall":False},
    {"on":False,"location":[3,9], "visible":False, "explored":False, "wall":False},
    {"on":False,"location":[4,9], "visible":False, "explored":False, "wall":False},
    {"on":False,"location":[5,9], "visible":False, "explored":False, "wall":False},
    {"on":False,"location":[6,9], "visible":False, "explored":False, "wall":False},
    {"on":False,"location":[7,9], "visible":False, "explored":False, "wall":False},
    {"on":False,"location":[8,9], "visible":False, "explored":False, "wall":False},
    {"on":False,"location":[9,9], "visible":False, "explored":False, "wall":False},
]